# Generated by Django 3.0 on 2020-02-09 01:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SocialMediaEndpoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='SocialMediaType',
            fields=[
                ('code', models.CharField(max_length=150, primary_key=True, serialize=False, unique=True)),
                ('Website', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='WebIdentity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
                ('About', models.TextField(blank=True)),
                ('Homepage', models.URLField(blank=True, null=True)),
                ('social', models.ManyToManyField(related_name='identities', to='web_presence.SocialMediaEndpoint')),
            ],
        ),
        migrations.AddField(
            model_name='socialmediaendpoint',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='endpoints', to='web_presence.SocialMediaType'),
        ),
    ]
