# Generated by Django 3.0 on 2020-02-09 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_presence', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialmediatype',
            name='icon',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
