# Generated by Django 3.0 on 2020-02-09 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_presence', '0002_socialmediatype_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='webidentity',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
