# Generated by Django 3.0 on 2020-02-15 16:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web_presence', '0003_webidentity_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='socialmediatype',
            old_name='Website',
            new_name='domain',
        ),
        migrations.RenameField(
            model_name='webidentity',
            old_name='About',
            new_name='about',
        ),
        migrations.RenameField(
            model_name='webidentity',
            old_name='Homepage',
            new_name='homepage',
        ),
        migrations.RemoveField(
            model_name='socialmediaendpoint',
            name='id',
        ),
        migrations.RemoveField(
            model_name='webidentity',
            name='Name',
        ),
        migrations.RemoveField(
            model_name='webidentity',
            name='email',
        ),
        migrations.RemoveField(
            model_name='webidentity',
            name='social',
        ),
        migrations.AddField(
            model_name='socialmediaendpoint',
            name='identity',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='social_networks', to='web_presence.WebIdentity'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='webidentity',
            name='first_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='webidentity',
            name='last_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='socialmediaendpoint',
            name='url',
            field=models.URLField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='socialmediatype',
            name='code',
            field=models.CharField(max_length=150, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='WebIdentityPenName',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('identity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pen_names', to='web_presence.WebIdentity')),
            ],
        ),
        migrations.CreateModel(
            name='WebIdentityEmail',
            fields=[
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('identity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emails', to='web_presence.WebIdentity')),
            ],
        ),
    ]
