# Generated by Django 3.0 on 2020-02-15 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_presence', '0004_auto_20200215_1624'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='webidentitypenname',
            name='identity',
        ),
        migrations.DeleteModel(
            name='WebIdentityEmail',
        ),
        migrations.DeleteModel(
            name='WebIdentityPenName',
        ),
    ]
