# Generated by Django 3.0 on 2020-02-08 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rss', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feed',
            name='Description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='feed',
            name='Name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='feed',
            name='url',
            field=models.URLField(default='https://www.xkcd.com/rss.xml'),
            preserve_default=False,
        ),
    ]
