# Generated by Django 3.0 on 2020-02-09 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rss', '0002_auto_20200208_1935'),
    ]

    operations = [
        migrations.AddField(
            model_name='feed',
            name='ETag',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='feed',
            name='Last Modified',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
