# Generated by Django 3.0 on 2020-02-09 21:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web_presence', '0003_webidentity_email'),
        ('rss', '0003_auto_20200209_0128'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField()),
                ('Source', models.URLField(blank=True)),
                ('Image Link', models.URLField(blank=True)),
                ('width', models.IntegerField(editable=False)),
                ('height', models.IntegerField(editable=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='feed',
            name='url',
        ),
        migrations.AddField(
            model_name='feed',
            name='Copywrite',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='feed',
            name='Home',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='feed',
            name='Icon',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='feed',
            name='License',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='feed',
            name='Logo',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='feed',
            name='Published',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='feed',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feeds', to='web_presence.WebIdentity'),
        ),
        migrations.AddField(
            model_name='feed',
            name='contributors',
            field=models.ManyToManyField(blank=True, null=True, related_name='feed_contributions', to='web_presence.WebIdentity'),
        ),
        migrations.AddField(
            model_name='feed',
            name='feed_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='feed',
            name='publisher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='publications', to='web_presence.WebIdentity'),
        ),
        migrations.AddField(
            model_name='feed',
            name='source',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='feed',
            name='subtitle',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='feed',
            name='title',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='feed',
            name='ETag',
            field=models.CharField(blank=True, editable=False, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='feed',
            name='Last Modified',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='feed',
            name='Image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feed', to='rss.FeedImage'),
        ),
    ]
