# Generated by Django 3.0 on 2020-02-09 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rss', '0004_auto_20200209_2122'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feed',
            old_name='Copywrite',
            new_name='copywrite',
        ),
        migrations.RenameField(
            model_name='feed',
            old_name='Description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='feed',
            old_name='ETag',
            new_name='etag',
        ),
        migrations.RenameField(
            model_name='feed',
            old_name='Home',
            new_name='home',
        ),
        migrations.RenameField(
            model_name='feed',
            old_name='Icon',
            new_name='icon',
        ),
        migrations.RenameField(
            model_name='feed',
            old_name='Last Modified',
            new_name='last_modified',
        ),
        migrations.RenameField(
            model_name='feed',
            old_name='License',
            new_name='license',
        ),
        migrations.RenameField(
            model_name='feed',
            old_name='Logo',
            new_name='logo',
        ),
        migrations.RenameField(
            model_name='feed',
            old_name='Name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='feed',
            old_name='Published',
            new_name='published',
        ),
    ]
