# Generated by Django 3.0 on 2020-02-15 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rss', '0005_auto_20200209_2134'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feed',
            name='name',
        ),
    ]
