# Generated by Django 3.0 on 2020-02-15 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rss', '0006_remove_feed_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedimage',
            old_name='Image Link',
            new_name='image_link',
        ),
        migrations.RenameField(
            model_name='feedimage',
            old_name='Source',
            new_name='src',
        ),
    ]
