# Generated by Django 3.0 on 2020-02-15 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rss', '0007_auto_20200215_1624'),
    ]

    operations = [
        migrations.CreateModel(
            name='PenName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
            ],
        ),
        migrations.AlterField(
            model_name='feed',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feeds', to='rss.PenName'),
        ),
        migrations.AlterField(
            model_name='feed',
            name='contributors',
            field=models.ManyToManyField(blank=True, null=True, related_name='feed_contributions', to='rss.PenName'),
        ),
        migrations.AlterField(
            model_name='feed',
            name='publisher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='publications', to='rss.PenName'),
        ),
    ]
