# Generated by Django 3.0 on 2020-02-15 21:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rss', '0008_auto_20200215_1716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feed',
            name='source',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='feed',
            name='subtitle',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='feed',
            name='title',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='FeedEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True)),
                ('entry_id', models.UUIDField(blank=True, null=True)),
                ('link', models.URLField(blank=True)),
                ('license', models.URLField(blank=True)),
                ('published', models.DateTimeField(null=True)),
                ('created', models.DateTimeField(null=True)),
                ('updated', models.DateTimeField(null=True)),
                ('comments', models.URLField(blank=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entries', to='rss.PenName')),
                ('contributors', models.ManyToManyField(blank=True, null=True, related_name='entry_contributions', to='rss.PenName')),
                ('publisher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entry_publications', to='rss.PenName')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='rss.Feed')),
            ],
            options={
                'unique_together': {('title', 'source')},
            },
        ),
        migrations.CreateModel(
            name='EntryContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base', models.URLField(blank=True)),
                ('language', models.TextField(blank=True)),
                ('value', models.TextField(blank=True)),
                ('type', models.TextField(blank=True)),
                ('entry', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='content', to='rss.FeedEntry')),
            ],
        ),
    ]
