# Generated by Django 3.0 on 2020-02-15 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rss', '0009_auto_20200215_2135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feed',
            name='contributors',
            field=models.ManyToManyField(blank=True, related_name='feed_contributions', to='rss.PenName'),
        ),
        migrations.AlterField(
            model_name='feedentry',
            name='contributors',
            field=models.ManyToManyField(blank=True, related_name='entry_contributions', to='rss.PenName'),
        ),
    ]
