# Generated by Django 3.0 on 2020-02-15 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rss', '0010_auto_20200215_2136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedentry',
            name='entry_id',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='feedimage',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
