# Generated by Django 3.0 on 2020-02-15 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rss', '0012_auto_20200215_2156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedimage',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
