# Generated by Django 3.0 on 2020-02-16 21:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rss', '0016_auto_20200215_2213'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feed',
            name='Image',
        ),
        migrations.AddField(
            model_name='feed',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feed', to='rss.FeedImage'),
        ),
        migrations.AlterField(
            model_name='entrycontent',
            name='language',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='entrycontent',
            name='type',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='feed',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feeds', to='rss.PenName'),
        ),
        migrations.AlterField(
            model_name='feed',
            name='contributors',
            field=models.ManyToManyField(blank=True, null=True, related_name='feed_contributions', to='rss.PenName'),
        ),
        migrations.AlterField(
            model_name='feed',
            name='copywrite',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='feed',
            name='etag',
            field=models.CharField(blank=True, editable=False, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='feed',
            name='published',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='feed',
            name='publisher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='publications', to='rss.PenName'),
        ),
        migrations.AlterField(
            model_name='feed',
            name='source',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='feed',
            name='subtitle',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='feed',
            name='title',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='feedentry',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entries', to='rss.PenName'),
        ),
        migrations.AlterField(
            model_name='feedentry',
            name='comments',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='feedentry',
            name='created',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='feedentry',
            name='entry_id',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='feedentry',
            name='published',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='feedentry',
            name='publisher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entry_publications', to='rss.PenName'),
        ),
        migrations.AlterField(
            model_name='feedentry',
            name='title',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='feedentry',
            name='updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
