# Generated by Django 3.0 on 2020-02-16 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rss', '0017_auto_20200216_2138'),
    ]

    operations = [
        migrations.AddField(
            model_name='feed',
            name='last_synced',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
    ]
