# Generated by Django 3.0 on 2020-02-16 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rss', '0018_feed_last_synced'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feed',
            name='last_modified',
            field=models.CharField(blank=True, editable=False, max_length=120, null=True),
        ),
    ]
