# Generated by Django 3.0 on 2020-02-16 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rss', '0019_auto_20200216_2241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feed',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
