# Generated by Django 3.0 on 2020-02-16 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rss', '0020_auto_20200216_2242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feed',
            name='contributors',
            field=models.ManyToManyField(blank=True, related_name='feed_contributions', to='rss.PenName'),
        ),
        migrations.AlterField(
            model_name='feed',
            name='copywrite',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='feed',
            name='home',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='feed',
            name='icon',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='feed',
            name='license',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='feed',
            name='logo',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='feedentry',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
