# Generated by Django 3.0 on 2020-02-16 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rss', '0021_auto_20200216_2245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feed',
            name='subtitle',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
