# Generated by Django 3.0 on 2020-02-16 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rss', '0022_auto_20200216_2255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedimage',
            name='image_link',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='feedimage',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
